---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: website-app-operator
  template:
    metadata:
      labels:
        name: website-app-operator
    spec:
      serviceAccountName: website-app
      containers:
        - name: website-app-operator
          image: quay.io/shubhamkatara/openshift-website-operator
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "website-app-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
